export function getContent(sectionId) {
    if (sectionId === 'home') {
        return `<h2>Home</h2><p>Non architecto dolore tempore eos rem illo voluptates corporis consequuntur dignissimos ratione vero rerum, similique necessitatibus quibusdam eum dicta atque minima doloribus numquam nostrum ipsa sint deserunt! Consectetur earum harum culpa impedit nisi, neque distinctio mollitia laborum voluptatem amet obcaecati soluta enim atque tempore minima eveniet. Sit iure voluptas officiis minima enim deserunt aliquam, sint iste numquam illum dolore cupiditate soluta qui recusandae alias unde ipsam exercitationem adipisci quia delectus perferendis. Hic, quidem ea. Aut ipsam nam unde. Voluptates dolore aut voluptatem consectetur minus rerum nisi? Sed delectus nesciunt culpa voluptate magnam expedita modi error dolorem obcaecati, et numquam quidem quod laborum mollitia necessitatibus ex ipsam quo animi reiciendis dignissimos molestias impedit sit libero natus. Corrupti aliquam harum, delectus maiores dolorum est esse cupiditate unde ex nobis provident iste vitae officia tenetur, eligendi nesciunt veritatis fugit tempora? Quo nam incidunt praesentium modi nulla delectus dignissimos earum ab possimus perspiciatis voluptates vel impedit, soluta ipsa obcaecati eaque eos debitis! Ullam esse optio magnam aut sint culpa nihil at fuga similique veritatis cupiditate corporis, omnis pariatur. Facere autem consectetur, accusamus praesentium earum quos, quia doloremque, culpa perferendis placeat ipsam mollitia provident deserunt iusto inventore aspernatur commodi sit! Excepturi dolore voluptatibus ut numquam esse nihil, quia eligendi quo nulla consequuntur!</p>`;
    } else if (sectionId === 'contact') {
        return '<h2>Contact</h2><p>Enim vel quo tenetur at repellendus. Aliquam impedit illum laboriosam, corporis fuga blanditiis nisi, voluptate magnam et unde soluta fugiat eligendi temporibus? Inventore suscipit soluta cupiditate, voluptatem adipisci alias, tempora aspernatur, beatae architecto quisquam consectetur odit necessitatibus dignissimos ipsa placeat quam vitae voluptates autem quos animi nulla nobis aut. Velit, enim voluptates illo assumenda magni doloremque vitae voluptatem dolor mollitia voluptas rem soluta officiis quos recusandae consequatur obcaecati adipisci deleniti suscipit? Earum, quasi nam quidem aliquid quas incidunt nulla, assumenda odio tempora aperiam id repudiandae. Dolore quisquam ipsa neque facilis explicabo. At similique, nostrum illum accusamus totam expedita voluptatum cum corporis quidem vero magni quo aut. Repellendus nihil optio perferendis pariatur sed, esse voluptates incidunt ut, amet voluptas in nobis commodi quis vero beatae? Fugit, doloribus eos?</p>';
    } else if (sectionId === 'information') {
        return '<h2>Information</h2><p>Tempore nobis et consectetur, assumenda veniam error aliquid autem. Dolores sequi molestiae labore architecto repudiandae beatae nisi consequuntur voluptatem in sunt perferendis, deleniti debitis repellendus impedit vel eveniet ea suscipit ipsam officiis! Praesentium, sequi a quam nam ducimus omnis at illo odit. Provident, quo et dignissimos asperiores neque veniam officiis assumenda voluptate dolore officia atque fuga iure reiciendis perferendis exercitationem ipsum, iusto maxime voluptates. Rem aliquid facere, praesentium laboriosam nisi asperiores ea similique sint. Aliquid porro autem aliquam distinctio aspernatur deserunt optio, eum harum eos, laboriosam labore minima maiores vel vero ea adipisci quis sed. Velit, delectus illo. Deserunt expedita adipisci incidunt id quidem labore ipsa excepturi quam itaque quo! Quos doloribus, repellat facere voluptates ea magnam necessitatibus debitis! voluptatem in sunt perferendis, deleniti debitis repellendus impedit vel eveniet ea suscipit ipsam officiis! Praesentium, sequi a quam nam ducimus omnis at illo odit. ';
    } else if (sectionId === 'guide') {
        return '<h2>Guide</h2><p> Fugit perspiciatis quaerat cumque error explicabo soluta dicta porro excepturi minima dignissimos autem ipsam vitae aliquam aliquid molestias non enim iste, quo ut! Eligendi ipsa corporis distinctio ullam nemo illo, nisi neque cum facilis deserunt, deleniti error veritatis? Assumenda soluta, vero recusandae minima provident deleniti, accusantium ab nostrum facere eveniet beatae pariatur quasi fugiat natus voluptatum explicabo adipisci dignissimos aliquid dolores fuga! Mollitia consequatur recusandae consectetur atque? Id magni voluptas quaerat qui dicta ipsum commodi, beatae quasi! Distinctio perspiciatis vel, earum natus voluptatum inventore deleniti, sed autem animi assumenda magnam, iusto porro! Odit quibusdam accusamus similique sapiente corrupti. Molestias nesciunt quasi, omnis nemo sequi doloribus labore laudantium doloremque! Non fuga voluptatibus nulla itaque recusandae optio ullam sunt, quae eos, vero nam culpa! Culpa id esse asperiores eum sapiente odit qui mollitia hic placeat et? Vitae ipsa, perferendis labore officiis culpa dolore nobis illo vel laborum at excepturi aliquid sed quisquam possimus non sit illum vero quis optio ad consectetur et error? </p>';
    }
    else {
        return '<h2>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias odit impedit harum? Aliquid obcaecati culpa ipsam voluptatibus qui, quibusdam doloremque saepe cumque perferendis nobis delectus corporis enim cupiditate fugiat sint ullam aperiam est suscipit inventore commodi iusto! Vero dolores distinctio magni laboriosam eaque reiciendis? Enim obcaecati, ducimus sunt distinctio suscipit, dignissimos, minus magnam recusandae dolores culpa ratione beatae exercitationem placeat harum molestiae laboriosam sit. Harum facere fugiat cumque quaerat distinctio rem eum? Velit porro, optio, ab architecto sed quas molestias quasi illo debitis accusantium veniam, dolores nesciunt eos nihil nam ex cum ipsum?</p>';
    }
}